implement photos
foxt/icloud.js pull request #3
Opened 2022-11-23 20:17 UTC by dez64ru

Implemented Photos service

2022-11-23 21:07 UTC, foxt commented
Hi, appreciative of your PR, looks good however there are two tiny nitpicks I'd like to make, whih I'd like to check in with you about?

Nevertheless I'd like to thank you for your contributions to this project.

2022-11-24 06:50 UTC, dez64ru commented
@foxt yeah, sure, feel free to request changes!

2022-11-24 08:03 UTC, foxt requested changes

2022-11-24 12:49 UTC, foxt approved these changes

2022-11-24 12:49 UTC, merged